### ISSUE TITLE
Submitting a vote on bugs.php.net results with a blank page

### ISSUE THREAD

**Issue by mvorisek** [php/web-bugs#112]
I did some experiments and it seems the issue is present when user is connected via IPv6. Database column length is probably too short.

**Comment by nikic** [comment]
Looking at the error log, it's even worse: https://github.com/php/web-bugs/blob/3fb5cb12012a3d6500846903a5790ef9190781fb/www/vote.php#L63 returns false and gets converted to empty string and we get an SQL syntax error :)

**Comment by cmb69** [comment]
… unless there is an X-Forwarded-For header involved, in which case the function might not return at all:
https://github.com/php/web-bugs/blob/3fb5cb12012a3d6500846903a5790ef9190781fb/www/vote.php#L53

Anyhow, I don't think it makes sense to fix that voting functionality. Maybe we should drop it altogether, see PR #120,

**Comment by derickr** [comment]
Will be addressed as part of #114 and #120
